version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: leavemng-backend
    env_file:
      - ./backend/.env.prod
      # Production environment (commented out for dev)
      # - ./backend/.env.prod
    expose:
      - "8000"
    volumes:
      - ./files:/app/app/api/uploads/
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: leavemng-frontend
    expose:
      - "80"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    environment:
      # Development environment
      - NODE_ENV=development
      # Production environment (commented out for dev)
      # - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: leavemng-proxy
    ports:
      - "80:80"
      # SSL port commented out for development (no SSL cert)
      # - "443:443"
    volumes:
      # Development nginx config (no SSL)
      - ./nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf
      # Production nginx config with SSL (commented out for dev)
      # - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      # - ../certs:/etc/ssl/private
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  pgdata:
  leavemng_files: