"""Change audit_logs.resource_id to UUID

Revision ID: 52d292665624
Revises: 471604c942d0
Create Date: 2025-05-01 19:35:49.355009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d292665624'
down_revision: Union[str, None] = '471604c942d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'resource_id')
    # Add the new column as UUID
    op.add_column(
        'audit_logs',
        sa.Column(
            'resource_id',
            sa.dialects.postgresql.UUID(
                as_uuid=True),
            nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE audit_logs ALTER COLUMN resource_id TYPE UUID USING resource_id::uuid')
    # ### end Alembic commands ###
