"""Add gender column to users

Revision ID: f7a882b00958
Revises: 2146e0c5646c
Create Date: 2025-05-06 14:47:34.965347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a882b00958'
down_revision: Union[str, None] = '2146e0c5646c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add as nullable with default 'male'
    op.add_column(
        'users',
        sa.Column(
            'gender',
            sa.String(),
            nullable=True,
            server_default='male'))
    # 2. Update all existing rows to 'male' (in case server_default does not
    # backfill)
    op.execute("UPDATE users SET gender = 'male' WHERE gender IS NULL")
    # 3. Alter to NOT NULL
    op.alter_column('users', 'gender', nullable=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
