name: Bandit Security Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'Development_Main'

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit security scan
        run: |
          bandit -r . -x "*/tests/*,*/migrations/*" --skip B101,B311,B404,B603,B607
