name: Deploy-Dev

on:
  push:
    branches: [ Development_Main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:   
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_PORT || 22 }}
        script: |
          # Navigate to project directory
          cd /leavemng
          
          # Pull latest code
          echo "Pulling latest code..."
          git pull origin Development_Main
          
          # Stop and remove containers
          docker stop leavemng-backend leavemng-frontend || true
          docker rm leavemng-backend leavemng-frontend || true
          
          # Remove old images
          docker rmi leavemng-backend leavemng-frontend || true
          
          # Start containers using Docker Compose
          docker compose -f docker-compose.dev.yml up -d --build --force-recreate
          
          # Wait for containers to become healthy
          echo "Waiting for containers to become healthy..."
          sleep 30
          
          # Verify deployment
          echo "Verifying deployment..."
          docker ps
          
          # Check if containers are healthy
          if docker ps | grep -q "leavemng-backend.*Up" && docker ps | grep -q "leavemng-frontend.*Up"; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed - containers not running properly"
            docker logs leavemng-backend --tail 50
            docker logs leavemng-frontend --tail 50
            exit 1
          fi